export const documentos = [
  {
    id: 1,
    titulo: "Proyecto Civil 1",
    tipo: "Informe",
    fecha: "2025-01-22",
    unidadAcademica: "Facultad de Derecho",
    departamento: "Civil",
    url: "/archivos/civil/Proyecto1.pdf",
    metadata: {
      autor: "Ana Gómez",
      palabrasClave: ["derecho", "civil", "proyecto"],
      descripcion: "Primer informe del proyecto civil.",
    },
  },
  {
    id: 2,
    titulo: "Proyecto Civil 2",
    tipo: "Informe",
    fecha: "2025-01-23",
    unidadAcademica: "Facultad de Derecho",
    departamento: "Civil",
    url: "/archivos/civil/Proyecto2.pdf",
    metadata: {
      autor: "Juan Pérez",
      palabrasClave: ["derecho", "civil", "proyecto"],
      descripcion: "Segundo informe del proyecto civil.",
    },
  },
  {
    id: 3,
    titulo: "Estudio Electrónica 1",
    tipo: "Tesis",
    fecha: "2025-01-21",
    unidadAcademica: "Facultad de Ingeniería",
    departamento: "Electrónica",
    url: "/archivos/electronica/Archivo1.pdf",
    metadata: {
      autor: "Luis Martínez",
      palabrasClave: ["ingeniería", "electrónica", "tesis"],
      descripcion: "Estudio técnico sobre electrónica.",
    },
  },
  {
    id: 4,
    titulo: "Estudio Electrónica 2",
    tipo: "Tesis",
    fecha: "2025-01-22",
    unidadAcademica: "Facultad de Ingeniería",
    departamento: "Electrónica",
    url: "/archivos/electronica/Archivo2.pdf",
    metadata: {
      autor: "María López",
      palabrasClave: ["ingeniería", "electrónica", "tesis"],
      descripcion: "Segundo estudio técnico sobre electrónica.",
    },
  },
  {
    id: 5,
    titulo: "Caso Penal 1",
    tipo: "Caso",
    fecha: "2025-01-20",
    unidadAcademica: "Facultad de Derecho",
    departamento: "Penal",
    url: "/archivos/penal/Caso1.pdf",
    metadata: {
      autor: "Carlos Fernández",
      palabrasClave: ["derecho", "penal", "caso"],
      descripcion: "Caso penal relacionado con derecho civil.",
    },
  },
  {
    id: 6,
    titulo: "Caso Penal 2",
    tipo: "Caso",
    fecha: "2025-01-21",
    unidadAcademica: "Facultad de Derecho",
    departamento: "Penal",
    url: "/archivos/penal/Caso2.pdf",
    metadata: {
      autor: "Laura Ramírez",
      palabrasClave: ["derecho", "penal", "jurídico"],
      descripcion: "Caso penal estudiado en derecho penal.",
    },
  },
  {
    id: 7,
    titulo: "Sistema Integrado 1",
    tipo: "Proyecto",
    fecha: "2025-01-18",
    unidadAcademica: "Facultad de Ingeniería",
    departamento: "Sistemas",
    url: "/archivos/sistemas/Archivo3.pdf",
    metadata: {
      autor: "Carlos Gómez",
      palabrasClave: ["sistemas", "ingeniería", "proyecto"],
      descripcion: "Proyecto de sistemas integrados - Parte 1.",
    },
  },
  {
    id: 8,
    titulo: "Sistema Integrado 2",
    tipo: "Proyecto",
    fecha: "2025-01-19",
    unidadAcademica: "Facultad de Ingeniería",
    departamento: "Sistemas",
    url: "/archivos/sistemas/Archivo4.pdf",
    metadata: {
      autor: "Elena Torres",
      palabrasClave: ["sistemas", "ingeniería", "tecnología"],
      descripcion: "Proyecto de sistemas integrados - Parte 2.",
    },
  },
  {
    id: 9,
    titulo: "La diabetes",
    tipo: "Tesina",
    fecha: "2024-01-19",
    unidadAcademica: "Facultad de Medicina",
    departamento: "Laboratorio",
    url: "/archivos/sistemas/Archivo4.pdf",
    metadata: {
      autor: "Elena Torres",
      palabrasClave: ["sistemas", "ingeniería", "tecnología"],
      descripcion: "Proyecto de sistemas integrados - Parte 2.",
    },
  },
];
